// Package mocks contains the mocks for the etrc trader bot service.
// These are generated by the gomock library and are used
// for testing the service.
//
// More information about how mocks are used in the project can be found
// in https://arexio.atlassian.net/wiki/spaces/ENG/pages/2845868036/Mocking
package mocks

// CustomMatcher defines a new matcher that can be used
// for manage more customs matches implementing the gomock.Matcher
// interfaces defined in the gomock library that we use
type CustomMatcher struct {
	Match func(x any) bool
}

// Matches it implements the Matches function defined
// as part of the gomock.Matcher interfaces, it runs the
// predefined Match function holded in the type
func (c CustomMatcher) Matches(x interface{}) bool {
	return c.Match(x)
}

func (c CustomMatcher) String() string {
	return "is equal to the Match function defined"
}
